export const ErrorCodes = {
  account_not_active: 'account_not_active',
  application_blocked: 'application_blocked',
  application_already_decided: 'application_already_decided',
  application_creation_failed: 'application_creation_failed',
  application_in_flight: 'application_in_flight',
  application_limit_reached: 'application_limit_reached',
  application_not_mutable: 'application_not_mutable',
  application_not_found: 'application_not_found',
  application_update_failed: 'application_update_failed',
  candidate_name_required: 'candidate_name_required',
  challenge_already_used: 'challenge_already_used',
  challenge_expired: 'challenge_expired',
  client_key_conflict: 'client_key_conflict',
  club_already_exists: 'club_already_exists',
  club_archive_expired: 'club_archive_expired',
  club_archive_not_found: 'club_archive_not_found',
  club_archived: 'club_archived',
  club_not_found: 'club_not_found',
  content_already_removed: 'content_already_removed',
  content_not_found: 'content_not_found',
  duplicate_vouch: 'duplicate_vouch',
  email_already_registered: 'email_already_registered',
  email_does_not_match_invite: 'email_does_not_match_invite',
  embedding_unavailable: 'embedding_unavailable',
  event_not_found: 'event_not_found',
  event_rsvp_closed: 'event_rsvp_closed',
  forbidden: 'forbidden',
  gate_rejected: 'gate_rejected',
  gate_unavailable: 'gate_unavailable',
  illegal_content: 'illegal_content',
  invalid_data: 'invalid_data',
  invalid_challenge: 'invalid_challenge',
  invalid_input: 'invalid_input',
  invalid_invitation_code: 'invalid_invitation_code',
  invalid_json: 'invalid_json',
  invalid_mentions: 'invalid_mentions',
  invalid_proof: 'invalid_proof',
  invalid_state_transition: 'invalid_state_transition',
  invalid_state: 'invalid_state',
  invitation_expired: 'invitation_expired',
  invitation_invalid: 'invitation_invalid',
  invitation_quota_exceeded: 'invitation_quota_exceeded',
  invitation_issue_failed: 'invitation_issue_failed',
  invitation_already_expired: 'invitation_already_expired',
  invitation_already_open: 'invitation_already_open',
  invitation_already_revoked: 'invitation_already_revoked',
  invitation_ambiguous: 'invitation_ambiguous',
  invitation_not_found: 'invitation_not_found',
  invitation_revoked: 'invitation_revoked',
  invitation_support_withdrawn: 'invitation_support_withdrawn',
  invitation_used: 'invitation_used',
  low_quality_content: 'low_quality_content',
  member_already_active: 'member_already_active',
  member_creation_failed: 'member_creation_failed',
  member_cap_below_current_count: 'member_cap_below_current_count',
  member_cap_reached: 'member_cap_reached',
  member_delete_blocked: 'member_delete_blocked',
  member_not_found: 'member_not_found',
  message_already_removed: 'message_already_removed',
  message_not_found: 'message_not_found',
  membership_exists: 'membership_exists',
  membership_not_found: 'membership_not_found',
  missing_row: 'missing_row',
  owner_club_limit_reached: 'owner_club_limit_reached',
  not_available: 'not_available',
  not_found: 'not_found',
  not_implemented: 'not_implemented',
  payload_too_large: 'payload_too_large',
  profile_not_found: 'profile_not_found',
  profile_generation_unavailable: 'profile_generation_unavailable',
  quota_exceeded: 'quota_exceeded',
  recipient_unavailable: 'recipient_unavailable',
  remove_requires_archived: 'remove_requires_archived',
  slug_conflict: 'slug_conflict',
  sponsor_not_found: 'sponsor_not_found',
  stale_client: 'stale_client',
  thread_not_found: 'thread_not_found',
  token_not_found: 'token_not_found',
  unauthorized: 'unauthorized',
  unknown_action: 'unknown_action',
  version_conflict: 'version_conflict',
  vouchee_not_accessible: 'vouchee_not_accessible',
  worker_fatal: 'worker_fatal',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

export const ERROR_STATUS: Record<ErrorCode, 400 | 401 | 403 | 404 | 409 | 413 | 422 | 429 | 500 | 501 | 503> = {
  account_not_active: 403,
  application_blocked: 403,
  application_already_decided: 409,
  application_creation_failed: 500,
  application_in_flight: 409,
  application_limit_reached: 429,
  application_not_mutable: 409,
  application_not_found: 404,
  application_update_failed: 500,
  candidate_name_required: 422,
  challenge_already_used: 422,
  challenge_expired: 422,
  client_key_conflict: 409,
  club_already_exists: 409,
  club_archive_expired: 409,
  club_archive_not_found: 404,
  club_archived: 409,
  club_not_found: 404,
  content_already_removed: 409,
  content_not_found: 404,
  duplicate_vouch: 409,
  email_already_registered: 409,
  email_does_not_match_invite: 409,
  embedding_unavailable: 503,
  event_not_found: 404,
  event_rsvp_closed: 409,
  forbidden: 403,
  gate_rejected: 422,
  gate_unavailable: 503,
  illegal_content: 422,
  invalid_data: 500,
  invalid_challenge: 422,
  invalid_input: 400,
  invalid_invitation_code: 422,
  invalid_json: 400,
  invalid_mentions: 409,
  invalid_proof: 422,
  invalid_state_transition: 409,
  invalid_state: 409,
  invitation_expired: 409,
  invitation_invalid: 404,
  invitation_quota_exceeded: 429,
  invitation_issue_failed: 500,
  invitation_already_expired: 409,
  invitation_already_open: 409,
  invitation_already_revoked: 409,
  invitation_ambiguous: 409,
  invitation_not_found: 404,
  invitation_revoked: 409,
  invitation_support_withdrawn: 409,
  invitation_used: 409,
  low_quality_content: 422,
  member_already_active: 409,
  member_creation_failed: 500,
  member_cap_below_current_count: 409,
  member_cap_reached: 409,
  member_delete_blocked: 409,
  member_not_found: 404,
  message_already_removed: 409,
  message_not_found: 404,
  membership_exists: 409,
  membership_not_found: 404,
  missing_row: 500,
  owner_club_limit_reached: 409,
  not_available: 501,
  not_found: 404,
  not_implemented: 501,
  payload_too_large: 413,
  profile_not_found: 404,
  profile_generation_unavailable: 503,
  quota_exceeded: 429,
  recipient_unavailable: 404,
  remove_requires_archived: 409,
  slug_conflict: 409,
  sponsor_not_found: 404,
  stale_client: 409,
  thread_not_found: 404,
  token_not_found: 404,
  unauthorized: 401,
  unknown_action: 400,
  version_conflict: 409,
  vouchee_not_accessible: 404,
  worker_fatal: 500,
};

export class AppError extends Error {
  statusCode: number;
  code: ErrorCode;
  kind?: string;
  requestTemplate?: unknown;
  details?: unknown;
  cause?: unknown;
  closeConnection?: boolean;

  constructor(code: ErrorCode, message: string, options?: { kind?: string; cause?: unknown; details?: unknown; closeConnection?: boolean }) {
    super(message);
    this.statusCode = ERROR_STATUS[code];
    this.code = code;
    this.kind = options?.kind;
    this.details = options?.details;
    this.cause = options?.cause;
    this.closeConnection = options?.closeConnection;
  }
}
